name: release
on:
  release:
    types: [published]
jobs:
  publish-python:
    runs-on: ubuntu-latest
    environment: PyPI
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          # Tags are needed to compute the current version number
          fetch-tags: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install Python build
        run: |
          pip install --upgrade pip
          pip install build
      - name: Build the Python distribution
        run: |
          python -m build
      - name: Build the Python client distribution
        # Place the output in the same directory, so it can all be uploaded together
        run: |
          python -m build --outdir ./dist ./python-client
      - name: Publish the Python distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  publish-javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Tags are needed to compute the current version number
          fetch-tags: true
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: current
      - name: Publish Javascript client to npm
        working-directory: ./javascript-client
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm ci
          npm version --no-git-tag-version $(git describe --tags --match '*[0-9]*' --abbrev=0 | sed 's/^v//')
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ./.npmrc
          npm publish
